version: '3.3'
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - 3365:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: espocrm
    volumes:
      - database:/var/lib/mysql

  phpfpm:
    image: php:1.0
    ports:
      - 9000:9000
    volumes:
     - ./index.php:/var/www/html/index.php
    environment:
      DB_HOST: mysqldb
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: espocrm
      DB_DRIVER: mysqldb:mysql
    links:
      - mysqldb:mysql

  webserver:
    image: nginx:alpine
    links:
      - phpfpm
    ports:
      - 8181:80
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html

volumes:
    database:

